version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-lambda-workflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xzbojilegrzh"
s3_prefix = "s3-lambda-workflow"
region = "cn-northwest-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
